name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: konekto/kronos:$(date +%s)
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.CI_REGISTRY_USER }}
          password: ${{ secrets.CI_REGISTRY_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push tagged now
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          target: production
          tags: konekto/kronos:$(date +%s)
      - name: Build and push tagged latest
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          target: production
          tags: konekto/kronos:latest
